spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
management.endpoints.web.exposure.include=health
spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=${DEFER_INIT:true}